"""事实层常量：状态、来源、派生对象、影响级别。不允许原地 Edit。"""

STATUS_EXTRACTED = "EXTRACTED"
STATUS_CONFIRMED = "CONFIRMED"
STATUS_REJECTED = "REJECTED"
STATUS_CONFLICT = "CONFLICT"
STATUS_SUPERSEDED = "SUPERSEDED"
STATUS_DELETED = "DELETED"

ACTIVE_FACT_STATUSES = (STATUS_EXTRACTED, STATUS_CONFIRMED, STATUS_CONFLICT)
TERMINAL_FACT_STATUSES = (STATUS_REJECTED, STATUS_SUPERSEDED, STATUS_DELETED)

STATUS_LABEL = {
    STATUS_EXTRACTED: "待确认",
    STATUS_CONFIRMED: "已确认",
    STATUS_REJECTED: "已驳回",
    STATUS_CONFLICT: "冲突",
    STATUS_SUPERSEDED: "已替代",
    STATUS_DELETED: "已删除",
}

FACT_TYPE_RELATION = "RELATION"
FACT_TYPE_EVENT = "EVENT"
FACT_TYPE_ATTRIBUTE = "ATTRIBUTE"
FACT_TYPE_DECISION = "DECISION"

SOURCE_DOCUMENT = "document"
SOURCE_EVENT = "event"
SOURCE_EXCEL = "excel"
SOURCE_MANUAL = "manual"
SOURCE_API = "api"
SOURCE_GRAPH = "graph_confirm"

METHOD_LLM = "llm_extract"
METHOD_MANUAL = "manual"
METHOD_IMPORT = "import"
METHOD_EVENT = "event"

KIND_GRAPH_NODE = "GRAPH_NODE"
KIND_GRAPH_RELATION = "GRAPH_RELATION"
KIND_PERSON_NETWORK = "PERSON_NETWORK"
KIND_TEAM_SITUATION = "TEAM_SITUATION"
KIND_ROLE_RANKING = "ROLE_RANKING"
KIND_PROMOTION = "PROMOTION"
KIND_INFLUENCE = "INFLUENCE"
KIND_DAILY_REPORT = "DAILY_REPORT"

KIND_LABEL = {
    KIND_GRAPH_NODE: "图谱实例",
    KIND_GRAPH_RELATION: "图谱关系",
    KIND_PERSON_NETWORK: "人物关系网",
    KIND_TEAM_SITUATION: "团队态势",
    KIND_ROLE_RANKING: "角色竞争",
    KIND_PROMOTION: "晋升推演",
    KIND_INFLUENCE: "影响力排名",
    KIND_DAILY_REPORT: "日报",
}

IMPACT_MUST_DELETE = "must_delete"
IMPACT_RECOMPUTE = "recompute"
IMPACT_STALE = "stale"
IMPACT_NONE = "none"

IMPACT_BY_KIND = {
    KIND_GRAPH_RELATION: IMPACT_MUST_DELETE,
    KIND_GRAPH_NODE: IMPACT_STALE,
    KIND_PERSON_NETWORK: IMPACT_RECOMPUTE,
    KIND_INFLUENCE: IMPACT_RECOMPUTE,
    KIND_TEAM_SITUATION: IMPACT_STALE,
    KIND_ROLE_RANKING: IMPACT_STALE,
    KIND_PROMOTION: IMPACT_STALE,
    KIND_DAILY_REPORT: IMPACT_NONE,
}

IMPACT_LABEL = {
    IMPACT_MUST_DELETE: "必须删除",
    IMPACT_RECOMPUTE: "必须重新计算",
    IMPACT_STALE: "建议重新分析",
    IMPACT_NONE: "无影响",
}

LINK_DIRECT = "DIRECT"
LINK_INDIRECT = "INDIRECT"

DERIVED_ACTIVE = "ACTIVE"
DERIVED_STALE = "STALE"
DERIVED_INVALID = "INVALID"
DERIVED_DELETED = "DELETED"

EXCLUSIVE_PREDICATES = frozenset({
    "OWNER", "ORG_RESPONSIBILITY", "RESPONSIBLE_FOR", "负责", "负责人",
    "REPORT_TO", "汇报", "MANAGEMENT_RESPONSIBILITY", "EXECUTION_RESPONSIBILITY",
})

PREDICATE_TO_ONTOLOGY = {
    "负责": "ORG_RESPONSIBILITY",
    "负责人": "ORG_RESPONSIBILITY",
    "OWNER": "ORG_RESPONSIBILITY",
    "ORG_RESPONSIBILITY": "ORG_RESPONSIBILITY",
    "组织责任": "ORG_RESPONSIBILITY",
    "执行责任": "EXECUTION_RESPONSIBILITY",
    "管理责任": "MANAGEMENT_RESPONSIBILITY",
    "汇报责任": "REPORTING_RESPONSIBILITY",
    "成果归属": "ACHIEVEMENT_OWNERSHIP",
    "技术贡献": "MADE_CONTRIBUTION",
    "架构贡献": "MADE_CONTRIBUTION",
    "EXECUTION_RESPONSIBILITY": "EXECUTION_RESPONSIBILITY",
    "管理责任": "MANAGEMENT_RESPONSIBILITY",
    "MANAGEMENT_RESPONSIBILITY": "MANAGEMENT_RESPONSIBILITY",
    "汇报责任": "REPORTING_RESPONSIBILITY",
    "REPORTING_RESPONSIBILITY": "REPORTING_RESPONSIBILITY",
    "协助": "SUPPORT",
    "支持": "SUPPORT",
    "SUPPORT": "SUPPORT",
    "参与": "PARTICIPATE",
    "PARTICIPATE": "PARTICIPATE",
    "协作": "COLLABORATE",
    "COLLABORATE": "COLLABORATE",
    "COLLABORATE_WITH": "COLLABORATE",
    "指导": "MENTOR",
    "MENTOR": "MENTOR",
    "汇报": "REPORT_TO",
    "REPORT_TO": "REPORT_TO",
    "分歧": "CONFLICT",
    "冲突": "CONFLICT",
    "CONFLICT": "CONFLICT",
    "协调": "COLLABORATE",
    "采用": "USES",
    "USES": "USES",
    "隶属": "BELONG_TO",
    "BELONG_TO": "BELONG_TO",
    "BELONGS_TO": "BELONG_TO",
}


def ontology_relation_of(predicate):
    key = (predicate or "").strip()
    return PREDICATE_TO_ONTOLOGY.get(key) or PREDICATE_TO_ONTOLOGY.get(key.upper()) or key or "RELATED"


GRAPH_REL_ALIASES = {
    "COLLABORATE": "COLLABORATE_WITH",
    "COLLABORATE_WITH": "COLLABORATE_WITH",
    "BELONG_TO": "BELONGS_TO",
    "BELONGS_TO": "BELONGS_TO",
    "PARTICIPATE": "WORKS_ON",
    "WORKS_ON": "WORKS_ON",
    "MANAGE": "MANAGEMENT_RESPONSIBILITY",
    "OWNER": "ORG_RESPONSIBILITY",
    "ORG_RESPONSIBILITY": "ORG_RESPONSIBILITY",
    "EXECUTION_RESPONSIBILITY": "EXECUTION_RESPONSIBILITY",
    "MANAGEMENT_RESPONSIBILITY": "MANAGEMENT_RESPONSIBILITY",
    "REPORTING_RESPONSIBILITY": "REPORTING_RESPONSIBILITY",
    "ACHIEVEMENT_OWNERSHIP": "ACHIEVEMENT_OWNERSHIP",
    "MADE_CONTRIBUTION": "MADE_CONTRIBUTION",
    "CONTRIBUTES_TO": "CONTRIBUTES_TO",
    "PERFORMED_TRAINING": "PERFORMED_TRAINING",
    "TRAINING_TARGET": "TRAINING_TARGET",
    "SUPPORT": "COLLABORATE_WITH",
    "USES": "HAS_KNOWLEDGE",
    "RELATED": "COLLABORATE_WITH",
}

GRAPH_OBJECT_TYPE = {
    "WORKS_ON": "Project",
    "OWNER": "Project",
    "ORG_RESPONSIBILITY": "Project",
    "EXECUTION_RESPONSIBILITY": "Project",
    "MANAGEMENT_RESPONSIBILITY": "Project",
    "REPORTING_RESPONSIBILITY": "Project",
    "ACHIEVEMENT_OWNERSHIP": "Achievement",
    "MADE_CONTRIBUTION": "Contribution",
    "CONTRIBUTES_TO": "Achievement",
    "PERFORMED_TRAINING": "TrainingAction",
    "TRAINING_TARGET": "Person",
    "EVIDENCES_CAPABILITY": "Capability",
    "HAS_CAPABILITY_EVIDENCE": "CapabilityEvidence",
    "INVOLVED_IN": "Event",
    "CONTROL_RESOURCE": "Resource",
    "HAS_RESOURCE": "Resource",
    "HAS_SUB_RESOURCE": "Resource",
    "HAS_ROLE": "Role",
    "HAS_KNOWLEDGE": "Knowledge",
    "BELONGS_TO": "Department",
}


def graph_relation_of(predicate):
    ont = ontology_relation_of(predicate)
    return GRAPH_REL_ALIASES.get(ont, ont)
